# Generated by Django 5.0.2 on 2024-04-21 07:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Phone number')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True, verbose_name='Gender')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ProfileImage/', verbose_name='Image')),
                ('joining', models.DateField(blank=True, null=True, verbose_name='Joining date')),
                ('termination', models.DateField(blank=True, null=True, verbose_name='Termination date')),
                ('user_salary', models.IntegerField(blank=True, default=0, null=True, verbose_name='User salary')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=10, verbose_name='User type')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
